import { addDays, format } from "date-fns";
import type { AppData, CalendarEvent, Course, Holiday, Job, Semester, TutorStudent, UserSettings } from "@/types";

const today = new Date();
const day = (offset: number) => format(addDays(today, offset), "yyyy-MM-dd");

export const categoryMeta = {
  course: { label: "大學課程", color: "#2563eb" },
  tutoring: { label: "家教", color: "#ef4444" },
  cram_school: { label: "補習班", color: "#f97316" },
  part_time: { label: "一般打工", color: "#84cc16" },
  lab: { label: "實驗室", color: "#06b6d4" },
  self_study: { label: "自習", color: "#8b5cf6" },
  exam: { label: "考試", color: "#991b1b" },
  assignment: { label: "作業期限", color: "#ca8a04" },
  personal: { label: "個人活動", color: "#64748b" },
  commute: { label: "交通", color: "#14b8a6" },
  rest: { label: "休息", color: "#94a3b8" },
  other: { label: "其他", color: "#475569" }
} as const;

export const defaultSettings: UserSettings = {
  userName: "林同學",
  schoolName: "範例大學",
  department: "化學系",
  semesterStart: "2026-09-01",
  semesterEnd: "2027-01-15",
  currency: "NT$",
  weekStartsOn: 1,
  timeFormat: "24h",
  dayStartTime: "08:00",
  dayEndTime: "23:00",
  minimumFreeMinutes: 60,
  tutorBufferMinutes: 30,
  commuteMinutes: 30,
  defaultPrepMinutes: 30,
  defaultReportMinutes: 15,
  avoidWorkPeriods: "週一 18:00 後、週五晚上",
  theme: "light",
  includeClassTimeInEffectiveRate: true,
  includePrepTimeInEffectiveRate: true,
  includeCommuteTimeInEffectiveRate: true,
  includeReportTimeInEffectiveRate: true
};

export const sampleCourses: Course[] = [
  {
    id: "course-organic",
    name: "有機化學",
    teacher: "陳教授",
    room: "理學院 302",
    weekday: 1,
    startTime: "09:00",
    endTime: "11:00",
    credits: 3,
    color: categoryMeta.course.color,
    notes: "每週小考",
    semesterStart: "2026-09-01",
    semesterEnd: "2027-01-15",
    semesterId: "semester-2026-fall",
    excludeNationalHolidays: true,
    excludeSchoolHolidays: true
  },
  {
    id: "course-pchem",
    name: "物理化學",
    teacher: "黃教授",
    room: "理學院 210",
    weekday: 2,
    startTime: "10:00",
    endTime: "12:00",
    credits: 3,
    color: "#0ea5e9",
    notes: "作業隔週交",
    semesterStart: "2026-09-01",
    semesterEnd: "2027-01-15",
    semesterId: "semester-2026-fall",
    excludeNationalHolidays: true,
    excludeSchoolHolidays: true
  },
  {
    id: "course-instrument",
    name: "儀器分析",
    teacher: "林教授",
    room: "實驗大樓 4F",
    weekday: 4,
    startTime: "13:00",
    endTime: "15:00",
    credits: 3,
    color: "#6366f1",
    notes: "需預習講義",
    semesterStart: "2026-09-01",
    semesterEnd: "2027-01-15",
    semesterId: "semester-2026-fall",
    excludeNationalHolidays: true,
    excludeSchoolHolidays: true
  },
  {
    id: "course-lab",
    name: "實驗課",
    teacher: "助教群",
    room: "化學實驗室",
    weekday: 5,
    startTime: "09:00",
    endTime: "12:00",
    credits: 2,
    color: categoryMeta.lab.color,
    notes: "穿實驗衣",
    semesterStart: "2026-09-01",
    semesterEnd: "2027-01-15",
    semesterId: "semester-2026-fall",
    excludeNationalHolidays: true,
    excludeSchoolHolidays: true
  }
];

export const sampleSemesters: Semester[] = [
  {
    id: "semester-2026-fall",
    name: "2026 學年度第一學期",
    startDate: "2026-09-01",
    endDate: "2027-01-15",
    isCurrent: true,
    classStartDate: "2026-09-14",
    classEndDate: "2027-01-15",
    notes: "示範學期，可在設定中修改"
  }
];

export const sampleHolidays: Holiday[] = [
  {
    id: "holiday-mid-autumn",
    date: "2026-09-25",
    name: "中秋節",
    type: "national",
    cancelsClasses: true,
    stopsFixedWork: false,
    notes: "示範國定假日"
  },
  {
    id: "holiday-school",
    date: "2026-10-10",
    name: "校內停課日",
    type: "school",
    cancelsClasses: true,
    stopsFixedWork: false,
    notes: "示範學校假日"
  }
];

export const sampleJobs: Job[] = [
  {
    id: "job-lab",
    name: "實驗室工讀",
    type: "lab",
    location: "材料實驗室",
    hourlyRate: 250,
    fixedHours: 5.5,
    reportBonus: 200,
    extraBonus: 0,
    defaultBonus: 200,
    defaultFixedPay: 0,
    defaultDurationMinutes: 330,
    defaultHourlyRate: 250,
    scheduleMode: "irregular",
    workOnNationalHolidays: false,
    workOnSchoolHolidays: false,
    defaultCancelOnHolidays: false,
    commuteMinutes: 15,
    prepMinutes: 0,
    reportMinutes: 30,
    contactName: "王助教",
    contactInfo: "lab@example.edu",
    payday: "每月 5 日",
    isActive: true,
    isPinned: true,
    notes: "完成報告可領獎金",
    color: categoryMeta.lab.color
  },
  {
    id: "job-xinzhuang",
    name: "新莊數學家教",
    type: "tutoring",
    location: "新莊",
    hourlyRate: 450,
    fixedHours: 3,
    reportBonus: 0,
    extraBonus: 0,
    defaultBonus: 0,
    defaultFixedPay: 0,
    defaultDurationMinutes: 180,
    defaultHourlyRate: 450,
    scheduleMode: "weekly",
    workOnNationalHolidays: false,
    workOnSchoolHolidays: false,
    defaultCancelOnHolidays: false,
    commuteMinutes: 60,
    prepMinutes: 30,
    reportMinutes: 20,
    contactName: "周媽媽",
    contactInfo: "LINE",
    payday: "每月最後一次上課",
    isActive: true,
    notes: "兄妹接續上課，各 1.5 小時",
    color: categoryMeta.tutoring.color,
    studentName: "周家兄妹",
    grade: "國二 / 小六",
    subject: "數學",
    parentContact: "LINE",
    weeklySchedule: "週三 18:30-21:30",
    materials: "翰林講義、自編練習",
    learningGoal: "穩定段考 85 分以上"
  },
  {
    id: "job-junior-math",
    name: "國中數學家教",
    type: "tutoring",
    location: "板橋",
    hourlyRate: 500,
    fixedHours: 2,
    reportBonus: 0,
    extraBonus: 0,
    defaultBonus: 0,
    defaultFixedPay: 0,
    defaultDurationMinutes: 120,
    defaultHourlyRate: 500,
    scheduleMode: "weekly",
    workOnNationalHolidays: false,
    workOnSchoolHolidays: false,
    defaultCancelOnHolidays: false,
    commuteMinutes: 40,
    prepMinutes: 30,
    reportMinutes: 15,
    contactName: "李爸爸",
    contactInfo: "電話",
    payday: "每月 10 日",
    isActive: true,
    notes: "加強代數",
    color: "#dc2626",
    studentName: "李宥辰",
    grade: "國三",
    subject: "數學",
    parentContact: "電話",
    weeklySchedule: "週二 19:00-21:00",
    materials: "康軒數學第三冊",
    learningGoal: "會考 A"
  },
  {
    id: "job-cram",
    name: "補習班",
    type: "cram_school",
    location: "台北車站",
    hourlyRate: 230,
    fixedHours: 3,
    reportBonus: 0,
    extraBonus: 0,
    defaultBonus: 0,
    defaultFixedPay: 0,
    defaultDurationMinutes: 180,
    defaultHourlyRate: 230,
    scheduleMode: "irregular",
    workOnNationalHolidays: false,
    workOnSchoolHolidays: false,
    defaultCancelOnHolidays: false,
    commuteMinutes: 35,
    prepMinutes: 0,
    reportMinutes: 0,
    contactName: "主任",
    contactInfo: "02-0000-0000",
    payday: "每月 15 日",
    isActive: true,
    notes: "櫃台與解題",
    color: categoryMeta.cram_school.color
  },
  {
    id: "job-weekend",
    name: "週末數學班",
    type: "cram_school",
    location: "線上",
    hourlyRate: 220,
    fixedHours: 2,
    reportBonus: 10,
    extraBonus: 0,
    defaultBonus: 10,
    defaultFixedPay: 0,
    defaultDurationMinutes: 120,
    defaultHourlyRate: 220,
    scheduleMode: "weekly",
    workOnNationalHolidays: false,
    workOnSchoolHolidays: false,
    defaultCancelOnHolidays: false,
    commuteMinutes: 0,
    prepMinutes: 20,
    reportMinutes: 10,
    contactName: "班主任",
    contactInfo: "email",
    payday: "每月 20 日",
    isActive: true,
    notes: "每次完成回報獎金 10 元",
    color: "#fb923c"
  }
];

export const sampleStudents: TutorStudent[] = [
  {
    id: "student-zhou",
    name: "周家兄妹",
    displayName: "周家",
    grade: "國二 / 小六",
    subject: "數學",
    weeklySchedule: "週三 18:30-21:30",
    hourlyRate: 450,
    defaultHourlyRate: 450,
    defaultDurationMinutes: 180,
    defaultBonus: 0,
    color: "#ef4444",
    location: "新莊",
    isActive: true,
    isPinned: true,
    scheduleMode: "weekly",
    scheduleWeekday: 3,
    scheduleStartTime: "18:30",
    scheduleEndTime: "21:30",
    scheduleEffectiveDate: "2026-09-01",
    scheduleEndDate: "2027-01-15",
    excludeNationalHolidays: false,
    excludeSchoolHolidays: false,
    parentContact: "LINE",
    learningGoal: "穩定段考 85 分以上",
    materials: "翰林講義、自編練習",
    currentProgress: "國中數學第三冊",
    progressPercent: 65,
    lastLessonDate: day(-3),
    nextLessonDate: day(4),
    weakUnits: "分式運算、幾何證明",
    notes: "哥哥需要更多應用題，妹妹計算速度快",
    jobId: "job-xinzhuang",
    records: [
      {
        id: "record-zhou-1",
        date: day(-3),
        chapter: "一元二次方程式",
        content: "公式解與基礎題型",
        performance: "公式使用逐漸熟悉，正負號仍需提醒",
        progressPercent: 65,
        homework: "講義 p.42-45",
        nextPlan: "應用題與錯題整理",
        parentReported: true,
        reportText: "今天完成一元二次方程式基礎題型，學生對公式使用已逐漸熟悉，但計算過程仍容易出現正負號錯誤。已安排相關練習，下次將進行應用題。",
        receivedReportBonus: false
      }
    ]
  },
  {
    id: "student-li",
    name: "李宥辰",
    displayName: "宥辰",
    grade: "國三",
    subject: "數學",
    weeklySchedule: "週二 19:00-21:00",
    hourlyRate: 500,
    defaultHourlyRate: 500,
    defaultDurationMinutes: 120,
    defaultBonus: 0,
    color: "#dc2626",
    location: "板橋",
    isActive: true,
    scheduleMode: "irregular",
    scheduleWeekday: 2,
    scheduleStartTime: "19:00",
    scheduleEndTime: "21:00",
    scheduleEffectiveDate: "2026-09-01",
    scheduleEndDate: "2027-01-15",
    excludeNationalHolidays: false,
    excludeSchoolHolidays: false,
    parentContact: "電話",
    learningGoal: "會考 A",
    materials: "康軒數學第三冊、歷屆試題",
    currentProgress: "二次函數",
    progressPercent: 42,
    lastLessonDate: day(-6),
    nextLessonDate: day(2),
    weakUnits: "函數圖形判讀、文字題",
    notes: "上課前先做 10 分鐘計算暖身",
    jobId: "job-junior-math",
    records: [
      {
        id: "record-li-1",
        date: day(-6),
        chapter: "二次函數圖形",
        content: "頂點式、開口方向與平移",
        performance: "觀念理解良好，題目敘述需要慢讀",
        progressPercent: 42,
        homework: "歷屆題 12 題",
        nextPlan: "混合題練習",
        parentReported: true,
        reportText: "今天練習二次函數圖形判讀，觀念理解良好，但遇到文字題時需要放慢讀題速度。已安排歷屆試題練習，下次會做混合題整理。",
        receivedReportBonus: false
      }
    ]
  }
];

export const sampleEvents: CalendarEvent[] = [
  {
    id: "event-organic",
    title: "有機化學",
    category: "course",
    start: `${day(1)}T09:00:00`,
    end: `${day(1)}T11:00:00`,
    location: "理學院 302",
    notes: "小考複習",
    repeatRule: { enabled: true, weekdays: [1], startDate: "2026-09-01", endDate: "2027-01-15" },
    countsForIncome: false,
    courseId: "course-organic",
    semesterId: "semester-2026-fall",
    status: "scheduled",
    color: categoryMeta.course.color,
    isCompleted: false,
    isPaid: false
  },
  {
    id: "event-lab-work",
    title: "實驗室工讀",
    category: "lab",
    start: `${day(0)}T13:30:00`,
    end: `${day(0)}T19:00:00`,
    location: "材料實驗室",
    notes: "完成報告",
    countsForIncome: true,
    hourlyRate: 250,
    bonus: 200,
    bonusEligible: true,
    bonusReceived: true,
    jobId: "job-lab",
    status: "completed",
    color: categoryMeta.lab.color,
    isCompleted: true,
    isPaid: false,
    payday: day(7)
  },
  {
    id: "event-xinzhuang",
    title: "新莊數學家教",
    category: "tutoring",
    start: `${day(3)}T18:30:00`,
    end: `${day(3)}T21:30:00`,
    location: "新莊",
    notes: "兄妹接續上課",
    countsForIncome: true,
    hourlyRate: 450,
    bonus: 0,
    bonusEligible: false,
    bonusReceived: false,
    jobId: "job-xinzhuang",
    studentId: "student-zhou",
    status: "scheduled",
    color: "#ef4444",
    isCompleted: false,
    isPaid: false,
    payday: day(14)
  },
  {
    id: "event-junior",
    title: "國中數學家教",
    category: "tutoring",
    start: `${day(2)}T19:00:00`,
    end: `${day(2)}T21:00:00`,
    location: "板橋",
    notes: "二次函數",
    countsForIncome: true,
    hourlyRate: 500,
    jobId: "job-junior-math",
    studentId: "student-li",
    status: "scheduled",
    color: "#dc2626",
    isCompleted: false,
    isPaid: false,
    payday: day(12)
  },
  {
    id: "event-cram",
    title: "補習班",
    category: "cram_school",
    start: `${day(5)}T14:00:00`,
    end: `${day(5)}T17:00:00`,
    location: "台北車站",
    notes: "櫃台與解題",
    countsForIncome: true,
    hourlyRate: 230,
    jobId: "job-cram",
    status: "scheduled",
    color: categoryMeta.cram_school.color,
    isCompleted: false,
    isPaid: false,
    payday: day(18)
  },
  {
    id: "event-study",
    title: "儀器分析報告",
    category: "self_study",
    start: `${day(1)}T20:00:00`,
    end: `${day(1)}T22:00:00`,
    location: "圖書館",
    notes: "整理數據",
    countsForIncome: false,
    status: "scheduled",
    isCompleted: false,
    isPaid: false
  }
];

export const sampleData: AppData = {
  storageVersion: 2,
  events: sampleEvents,
  courses: sampleCourses,
  jobs: sampleJobs,
  students: sampleStudents,
  semesters: sampleSemesters,
  holidays: sampleHolidays,
  settings: defaultSettings
};
